project:
  type: website
  output-dir: _site # Standard for GitHub Pages hosting

website:
  title: "FinRetain App"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: ui_design.qmd           
        text: "UI/UX Design"
      - href: storyboard.qmd            
        text: "Storyboard"
      - href: proposal.qmd
        text: "Proposal"
      - href: meeting.qmd
        text: "Minutes of Meeting"
      - text: "Methodology"
        menu:
          - href: data_prep.qmd
            text: "Data Preparation"
          - href: analysis.qmd
            text: "Exploratory Analysis"
      - href: findings.qmd
        text: "Findings & Discussion"
      - href: poster.qmd
        text: "Poster"
      - href: user-guide.qmd
        text: "User Guide"
    right:
      - icon: github
        href: https://github.com/kenlim0620/ISSS608-Team-15-Project
      - text: "Launch App ðŸš€"
        href: https://lin-xianwei.shinyapps.io/New-Shiny/ # Link to your separate Shiny App

page-footer:
    background: dark
    left: "LIN XIANWEI - Project Prototype"
    right: "Singapore Management University"
    
format:
  html:
    theme: lumen # Clean, professional, modern
    css: styles.css
    toc: true
    toc-depth: 3
    smooth-scroll: true
    highlight-style: github
    
execute:
  echo: true
  warning: false
  message: false
